/**
 * Accounts Payable Types
 * Type definitions for AP agent functionality
 */

/**
 * Supplier validation status
 */
export type SupplierStatus = "active" | "inactive" | "pending" | "blocked";

/**
 * Supplier risk level for payment operations
 */
export type SupplierRiskLevel = "low" | "medium" | "high" | "critical";

/**
 * Bill status in AP workflow
 */
export type BillStatus =
  | "draft"
  | "awaiting_approval"
  | "approved"
  | "disputed"
  | "paid"
  | "overdue"
  | "cancelled";

/**
 * GST tax codes for Australian businesses
 */
export type GSTCode =
  | "GST_FREE" // GST-free supply
  | "INPUT_TAX" // GST on purchases (10%)
  | "OUTPUT_TAX" // GST on sales (10%)
  | "BAS_EXCLUDED" // Not reportable on BAS
  | "CAPITAL_PURCHASE"; // Capital acquisition

/**
 * Approval status for bills
 */
export type ApprovalStatus =
  | "pending"
  | "approved"
  | "rejected"
  | "escalated"
  | "expired";

/**
 * Payment risk flags
 */
export type PaymentRiskFlag =
  | "missing_abn"
  | "missing_tax_invoice"
  | "duplicate_bill"
  | "unusual_amount"
  | "inactive_supplier"
  | "missing_approval"
  | "overdue_terms"
  | "bank_details_changed";

/**
 * Supplier information
 */
export type Supplier = {
  id: string;
  name: string;
  abn?: string;
  email?: string;
  phone?: string;
  status: SupplierStatus;
  riskLevel: SupplierRiskLevel;
  paymentTerms?: string;
  defaultAccount?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
};

/**
 * Bill line item with GST coding
 */
export type BillLineItem = {
  description: string;
  accountCode: string;
  accountName: string;
  quantity: number;
  unitAmount: number;
  lineAmount: number;
  taxType: string;
  taxAmount: number;
  gstCode?: GSTCode;
};

/**
 * Bill/invoice in AP system
 */
export type Bill = {
  id: string;
  supplierId: string;
  supplierName: string;
  billNumber: string;
  reference?: string;
  date: Date;
  dueDate: Date;
  status: BillStatus;
  subtotal: number;
  taxAmount: number;
  total: number;
  amountDue: number;
  lineItems: BillLineItem[];
  approvalStatus?: ApprovalStatus;
  approvedBy?: string;
  approvedAt?: Date;
  hasAttachment: boolean;
  attachmentUrl?: string;
  riskFlags: PaymentRiskFlag[];
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
};

/**
 * Bill coding suggestion from AI
 */
export type CodingSuggestion = {
  lineItemIndex: number;
  description: string;
  suggestedAccount: string;
  suggestedAccountName: string;
  suggestedGSTCode: GSTCode;
  confidence: number;
  reasoning: string;
};

/**
 * Bill approval workflow item
 */
export type ApprovalItem = {
  billId: string;
  billNumber: string;
  supplierName: string;
  amount: number;
  dueDate: Date;
  status: ApprovalStatus;
  requiredApprovers: string[];
  currentApprover?: string;
  approvalLevel: number;
  escalationDate?: Date;
  notes?: string;
};

/**
 * Payment batch for processing
 */
export type PaymentBatch = {
  id: string;
  name: string;
  paymentDate: Date;
  bills: Bill[];
  totalAmount: number;
  billCount: number;
  riskFlags: PaymentRiskFlag[];
  status: "draft" | "ready" | "processing" | "completed" | "failed";
  createdAt: Date;
};

/**
 * Payment proposal generated by agent
 */
export type PaymentProposal = {
  batchName: string;
  proposedDate: Date;
  bills: Array<{
    billId: string;
    billNumber: string;
    supplierName: string;
    amount: number;
    dueDate: Date;
    priority: "urgent" | "due_soon" | "normal";
  }>;
  totalAmount: number;
  billCount: number;
  riskSummary: {
    critical: number;
    high: number;
    medium: number;
    low: number;
  };
  recommendations: string[];
};

/**
 * Email draft artifact
 */
export type EmailDraft = {
  to: string;
  subject: string;
  body: string;
  attachments?: string[];
  purpose: "follow_up" | "reminder" | "query" | "payment_advice";
  createdAt: Date;
};

/**
 * Audit trail entry for AP operations
 */
export type AuditEntry = {
  id: string;
  entityType: "bill" | "supplier" | "payment" | "approval";
  entityId: string;
  action: string;
  userId: string;
  userName: string;
  changes?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  timestamp: Date;
};

/**
 * ABN validation result
 */
export type ABNValidation = {
  abn: string;
  isValid: boolean;
  entityName?: string;
  entityType?: string;
  gstRegistered?: boolean;
  message?: string;
};

/**
 * AP agent settings
 */
export type APAgentSettings = {
  model?: string;
  autoApprovalThreshold?: number; // Amount in dollars below which bills can be auto-approved
  requireABN?: boolean;
  gstValidation?: boolean;
  duplicateCheckDays?: number; // Number of days to check for duplicate bills
  defaultPaymentTerms?: string;
};

/**
 * Extracted invoice data from PDF/image processing
 */
export type ExtractedInvoiceData = {
  supplierName?: string;
  supplierABN?: string;
  supplierAddress?: string;
  supplierEmail?: string;
  supplierPhone?: string;
  invoiceNumber?: string;
  invoiceDate?: string; // YYYY-MM-DD
  dueDate?: string; // YYYY-MM-DD
  purchaseOrderNumber?: string;
  subtotal?: number;
  gstAmount?: number;
  totalAmount?: number;
  lineItems?: Array<{
    description: string;
    quantity?: number;
    unitPrice?: number;
    amount: number;
    gstIncluded?: boolean;
  }>;
  paymentTerms?: string;
  bankDetails?: {
    accountName?: string;
    bsb?: string;
    accountNumber?: string;
  };
  rawText?: string;
  confidence?: number; // 0-1 confidence score for extraction quality
  warnings?: string[]; // Any validation warnings or missing fields
};

/**
 * Vendor matching result
 */
export type VendorMatchResult = {
  matched: boolean;
  contact?: {
    contactId: string;
    name: string;
    email?: string;
    phone?: string;
    isSupplier: boolean;
  };
  suggestions?: Array<{
    contactId: string;
    name: string;
    similarity: number;
    email?: string;
  }>;
  shouldCreateNew?: boolean;
  proposedContact?: {
    name: string;
    email?: string;
    phone?: string;
    taxNumber?: string; // ABN
  };
};

/**
 * Invoice processing result
 */
export type InvoiceProcessingResult = {
  success: boolean;
  invoiceData?: ExtractedInvoiceData;
  vendorMatch?: VendorMatchResult;
  codingSuggestions?: CodingSuggestion[];
  duplicateCheck?: {
    isDuplicate: boolean;
    potentialDuplicates?: Array<{
      billId: string;
      billNumber: string;
      amount: number;
      date: string;
      similarity: number;
    }>;
  };
  riskAssessment?: {
    level: SupplierRiskLevel;
    flags: PaymentRiskFlag[];
    score: number;
    recommendations: string[];
  };
  xeroBillDraft?: {
    contactId?: string;
    contactName: string;
    invoiceNumber: string;
    date: string;
    dueDate: string;
    lineItems: Array<{
      description: string;
      quantity: number;
      unitAmount: number;
      accountCode?: string;
      taxType: string;
    }>;
    total: number;
  };
  error?: string;
  warnings?: string[];
};
