/**
 * Accounts Payable Types
 * Type definitions for AP agent functionality
 */

/**
 * Vendor validation status
 */
export type VendorStatus = "active" | "inactive" | "pending" | "blocked";

/**
 * Vendor risk level for payment operations
 */
export type VendorRiskLevel = "low" | "medium" | "high" | "critical";

/**
 * Bill status in AP workflow
 */
export type BillStatus =
  | "draft"
  | "awaiting_approval"
  | "approved"
  | "disputed"
  | "paid"
  | "overdue"
  | "cancelled";

/**
 * GST tax codes for Australian businesses
 */
export type GSTCode =
  | "GST_FREE" // GST-free supply
  | "INPUT_TAX" // GST on purchases (10%)
  | "OUTPUT_TAX" // GST on sales (10%)
  | "BAS_EXCLUDED" // Not reportable on BAS
  | "CAPITAL_PURCHASE"; // Capital acquisition

/**
 * Approval status for bills
 */
export type ApprovalStatus =
  | "pending"
  | "approved"
  | "rejected"
  | "escalated"
  | "expired";

/**
 * Payment risk flags
 */
export type PaymentRiskFlag =
  | "missing_abn"
  | "missing_tax_invoice"
  | "duplicate_bill"
  | "unusual_amount"
  | "inactive_vendor"
  | "missing_approval"
  | "overdue_terms"
  | "bank_details_changed";

/**
 * Vendor information
 */
export interface Vendor {
  id: string;
  name: string;
  abn?: string;
  email?: string;
  phone?: string;
  status: VendorStatus;
  riskLevel: VendorRiskLevel;
  paymentTerms?: string;
  defaultAccount?: string;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Bill line item with GST coding
 */
export interface BillLineItem {
  description: string;
  accountCode: string;
  accountName: string;
  quantity: number;
  unitAmount: number;
  lineAmount: number;
  taxType: string;
  taxAmount: number;
  gstCode?: GSTCode;
}

/**
 * Bill/invoice in AP system
 */
export interface Bill {
  id: string;
  vendorId: string;
  vendorName: string;
  billNumber: string;
  reference?: string;
  date: Date;
  dueDate: Date;
  status: BillStatus;
  subtotal: number;
  taxAmount: number;
  total: number;
  amountDue: number;
  lineItems: BillLineItem[];
  approvalStatus?: ApprovalStatus;
  approvedBy?: string;
  approvedAt?: Date;
  hasAttachment: boolean;
  attachmentUrl?: string;
  riskFlags: PaymentRiskFlag[];
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Bill coding suggestion from AI
 */
export interface CodingSuggestion {
  lineItemIndex: number;
  description: string;
  suggestedAccount: string;
  suggestedAccountName: string;
  suggestedGSTCode: GSTCode;
  confidence: number;
  reasoning: string;
}

/**
 * Bill approval workflow item
 */
export interface ApprovalItem {
  billId: string;
  billNumber: string;
  vendorName: string;
  amount: number;
  dueDate: Date;
  status: ApprovalStatus;
  requiredApprovers: string[];
  currentApprover?: string;
  approvalLevel: number;
  escalationDate?: Date;
  notes?: string;
}

/**
 * Payment batch for processing
 */
export interface PaymentBatch {
  id: string;
  name: string;
  paymentDate: Date;
  bills: Bill[];
  totalAmount: number;
  billCount: number;
  riskFlags: PaymentRiskFlag[];
  status: "draft" | "ready" | "processing" | "completed" | "failed";
  createdAt: Date;
}

/**
 * Payment proposal generated by agent
 */
export interface PaymentProposal {
  batchName: string;
  proposedDate: Date;
  bills: Array<{
    billId: string;
    billNumber: string;
    vendorName: string;
    amount: number;
    dueDate: Date;
    priority: "urgent" | "due_soon" | "normal";
  }>;
  totalAmount: number;
  billCount: number;
  riskSummary: {
    critical: number;
    high: number;
    medium: number;
    low: number;
  };
  recommendations: string[];
}

/**
 * Email draft artifact
 */
export interface EmailDraft {
  to: string;
  subject: string;
  body: string;
  attachments?: string[];
  purpose: "follow_up" | "reminder" | "query" | "payment_advice";
  createdAt: Date;
}

/**
 * Audit trail entry for AP operations
 */
export interface AuditEntry {
  id: string;
  entityType: "bill" | "vendor" | "payment" | "approval";
  entityId: string;
  action: string;
  userId: string;
  userName: string;
  changes?: Record<string, unknown>;
  metadata?: Record<string, unknown>;
  timestamp: Date;
}

/**
 * ABN validation result
 */
export interface ABNValidation {
  abn: string;
  isValid: boolean;
  entityName?: string;
  entityType?: string;
  gstRegistered?: boolean;
  message?: string;
}

/**
 * AP agent settings
 */
export interface APAgentSettings {
  model?: string;
  autoApprovalThreshold?: number; // Amount in dollars below which bills can be auto-approved
  requireABN?: boolean;
  gstValidation?: boolean;
  duplicateCheckDays?: number; // Number of days to check for duplicate bills
  defaultPaymentTerms?: string;
}
